Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/wenxuan/Stable-diffusion-for-book-cover-generation/sd-inference.py", line 399, in <module>
    pipeline = StableDiffusionPipeline.from_pretrained(
TypeError: from_pretrained() missing 1 required positional argument: 'pretrained_model_name_or_path'